services:
  - type: web
    name: discord-bot
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SOURCE_CHANNEL_ID
        sync: false
      - key: ARCHIVE_CHANNEL_ID
        sync: false
